import Config

# Configure your database
config :linkhut, Linkhut.Repo,
  username: "postgres",
  password: "postgres",
  database: "linkhut_dev",
  hostname: "localhost",
  port: 5432,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :linkhut, LinkhutWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    asset_copy: {Phoenix.Copy, :watch, [:default]},
    sass:
      {DartSass, :install_and_run,
       [:default, ~w(--embed-source-map --source-map-urls=absolute --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :linkhut, LinkhutWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/linkhut_web/{live,views}/.*(ex)$",
      ~r"lib/linkhut_web/templates/.*(eex)$"
    ]
  ]

# Enable dev routes
config :linkhut, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :linkhut, Linkhut.Mail, sender: {"linkhut", "no-reply@example.com"}

config :linkhut, Linkhut.Prometheus, username: "prometheus", password: "metrics"

config :linkhut, Linkhut.IFTTT, user_id: 0, application: "aaabbb", service_key: "cccddd"

config :linkhut, Linkhut.Archiving,
  mode: :limited,
  data_dir: "/tmp/store",
  serve_host: nil,
  storage: Linkhut.Archiving.Storage.S3

config :linkhut, Linkhut.Archiving.Storage.S3,
  bucket: "linkhut-dev",
  region: "eu-central-1",
  endpoint: "localhost",
  port: 9000,
  scheme: "http://",
  access_key_id: "miniouser",
  secret_access_key: "miniopassword",
  presign_ttl: 900,
  compression: :gzip
