defmodule Linkhut.LinksTest do
  use Linkhut.DataCase

  import Linkhut.Factory

  alias Linkhut.Links
  alias Linkhut.Links.Link
  alias Linkhut.Links.UrlDetail
  alias Linkhut.AccountsFixtures

  describe "create_link/2" do
    setup do
      user = AccountsFixtures.user_fixture()

      valid_attrs = %{
        url: "https://example.com/test",
        title: "Test Title",
        notes: "Some **markdown** content.",
        tags: ["elixir", "test"],
        is_private: true,
        is_unread: false
      }

      %{user: user, valid_attrs: valid_attrs}
    end

    test "successfully creates a link", %{user: user, valid_attrs: attrs} do
      assert {:ok, %Link{} = link} = Links.create_link(user, attrs)
      assert link.url == "https://example.com/test"
      assert link.title == "Test Title"
      assert link.notes == "Some **markdown** content."
    end

    test "requires url", %{user: user, valid_attrs: attrs} do
      required = [:url]

      for field <- required do
        invalid_attrs = Map.delete(attrs, field)
        {:error, changeset} = Links.create_link(user, invalid_attrs)
        refute changeset.valid?
        assert Access.get(errors_on(changeset), field) != []
      end
    end

    test "url must be valid with scheme and host", %{user: user} do
      for {invalid_url, error_msg} <- [
            {"example.com", "is missing a scheme"},
            {"https:", "is missing a host"},
            {"", "can't be blank"}
          ] do
        {:error, changeset} =
          Links.create_link(user, %{
            url: invalid_url,
            title: "Test",
            is_private: true
          })

        refute changeset.valid?
        assert %{url: [error]} = errors_on(changeset)
        assert error == error_msg
      end
    end

    test "notes generate notes_html", %{user: user, valid_attrs: attrs} do
      {:ok, link} = Links.create_link(user, attrs)

      assert link.notes_html =~ "<p>\nSome <strong>markdown</strong> content.</p>\n"
    end

    test "title is autogenerated from URL if not provided", %{user: user, valid_attrs: attrs} do
      for {html, idx} <-
            Enum.with_index([
              "<html><head><title>Fetched Title</title></head></html>",
              "<html><head><title>Not this title</title><meta property=\"og:title\" content=\"Fetched Title\" /></head></html>",
              "<html><body><h1>Fetched Title</h1><h1>Not the fetched title</h1></body></html>"
            ]) do
        Req.Test.stub(Linkhut.Links.Link, fn conn ->
          Req.Test.html(conn, html)
        end)

        attrs = Map.drop(attrs, [:title])
        attrs = Map.put(attrs, :url, "http://example.com/#{idx}")

        {:ok, link} = Links.create_link(user, attrs)
        assert link.url == "http://example.com/#{idx}"
        assert link.title == "Fetched Title"
      end
    end

    test "title fallback to path or host on failed fetch", %{user: user, valid_attrs: attrs} do
      for {url, title} <- [
            {"https://example.com/foo/bar.pdf", "bar.pdf"},
            {"https://example.com", "example.com"},
            {"https://foo.example.com", "foo.example.com"},
            {"http://localhost:8080", "localhost"},
            {"http://127.0.0.1:8080", "127.0.0.1"},
            {"http://10.0.0.1", "10.0.0.1"},
            {"http://192.168.0.1/", "192.168.0.1"},
            {"http://172.31.0.1/foo/", "foo"},
            {"http://[fc00::1]", "fc00::1"},
            {"http://[::1]:8080", "::1"}
          ] do
        Req.Test.stub(Linkhut.Links.Link, fn conn ->
          Req.Test.transport_error(conn, :closed)
        end)

        attrs = Map.drop(attrs, [:title])
        attrs = Map.put(attrs, :url, url)

        {:ok, link} = Links.create_link(user, attrs)
        assert link.title == title
      end
    end

    test "title is fallback to path or host on failed fetch", %{user: user, valid_attrs: attrs} do
      Req.Test.stub(Linkhut.Links.Link, fn conn ->
        Req.Test.transport_error(conn, :timeout)
      end)

      attrs = Map.drop(attrs, [:title])
      attrs = Map.put(attrs, :url, "https://example.com/foo/bar")

      {:ok, link} = Links.create_link(user, attrs)
      assert link.title == "bar"
    end

    test "deduplicates tags case-insensitively and preserves 'unread'", %{
      user: user,
      valid_attrs: attrs
    } do
      tags = ["Elixir", "elixir", "unread"]
      {:ok, link} = Links.create_link(user, Map.put(attrs, :tags, tags))
      assert link.tags == ["Elixir", "unread"]
    end

    test "adds 'unread' tag if is_unread is true", %{user: user, valid_attrs: attrs} do
      attrs = Map.put(attrs, :is_unread, true)
      {:ok, link} = Links.create_link(user, attrs)
      assert "unread" in link.tags
    end

    test "enforces max length on title and notes", %{user: user, valid_attrs: attrs} do
      {:error, changeset} =
        Links.create_link(user, %{
          attrs
          | title: String.duplicate("a", 300),
            notes: String.duplicate("b", 2000)
        })

      refute changeset.valid?
      assert "should be at most 255 character(s)" in errors_on(changeset).title
      assert "should be at most 1024 character(s)" in errors_on(changeset).notes
    end
  end

  describe "update_link/2" do
    setup context do
      user = AccountsFixtures.user_fixture()

      valid_attrs =
        %{
          url: "https://example.com/test",
          title: "Test Title",
          notes: "Some **markdown** content.",
          tags: ["elixir", "test"],
          is_private: true,
          is_unread: false
        }
        |> Map.merge(Map.get(context, :extra_attrs, %{}))

      {:ok, link} = Links.create_link(user, valid_attrs)

      %{user: user, link: link, valid_attrs: valid_attrs}
    end

    @tag extra_attrs: %{tags: ["unread"]}
    test "removes 'unread' tag if is_unread is false", %{link: link, valid_attrs: attrs} do
      attrs = Map.put(attrs, :is_unread, false)
      {:ok, link} = Links.update_link(link, attrs)
      refute "unread" in link.tags
      refute link.is_unread
    end

    test "is_unread is set if tags include 'unread'", %{link: link, valid_attrs: attrs} do
      attrs = Map.put(attrs, :tags, ["elixir", "unread"])
      {:ok, link} = Links.update_link(link, attrs)
      assert link.is_unread
    end
  end

  describe "link queries" do
    setup do
      user = AccountsFixtures.user_fixture()

      {:ok, link1} =
        Links.create_link(user, %{
          url: "https://example.com/1",
          title: "Example 1",
          tags: ["test"],
          is_private: false,
          is_unread: false
        })

      :timer.sleep(1000)

      {:ok, link2} =
        Links.create_link(user, %{
          url: "https://example.com/2",
          title: "Example 2",
          tags: ["test"],
          is_private: true,
          is_unread: false
        })

      :timer.sleep(1000)

      {:ok, link3} =
        Links.create_link(user, %{
          url: "https://example.com/3",
          title: "Example 3",
          tags: ["test"],
          is_private: false,
          is_unread: true
        })

      assert %{failure: 0} = Oban.drain_queue(queue: :default)

      %{user: user, links: [link1, link2, link3]}
    end

    test "get/2 returns link by URL and user_id", %{user: user} do
      assert %Link{} = link = Links.get("https://example.com/1", user.id)
      assert link.title == "Example 1"
    end

    test "get!/2 returns link or raises error", %{user: user} do
      assert %Link{} = Links.get!("https://example.com/1", user.id)

      assert_raise Ecto.NoResultsError, fn ->
        Links.get!("nonexistent", user.id)
      end
    end

    test "all/1 with user returns all user links", %{user: user} do
      links = Links.all(user)
      assert length(links) == 3
    end

    test "all/1 with visibility filter returns appropriate links", %{user: user} do
      public_links = Links.all(visible_as: :public)
      assert length(public_links) == 1

      user_visible_links = Links.all(visible_as: user.id)
      assert length(user_visible_links) == 3
    end

    test "unread_count/1 returns count of unread links", %{user: user} do
      assert Links.unread_count(user.id) == 1
    end

    test "most_recent/1 returns most recently modified link", %{user: user} do
      recent = Links.most_recent(user)
      assert recent.url == "https://example.com/3"
    end
  end

  describe "filtering and ordering" do
    setup do
      user = AccountsFixtures.user_fixture()

      {:ok, _} =
        Links.create_link(user, %{
          url: "https://example.com/1",
          title: "Example 1",
          tags: ["elixir"],
          inserted_at: DateTime.add(DateTime.utc_now(), -2, :day)
        })

      {:ok, _} =
        Links.create_link(user, %{
          url: "https://example.com/2",
          title: "Example 2",
          tags: ["elixir", "phoenix"]
        })

      %{user: user}
    end

    test "all/1 with tag filter returns matching links", %{user: user} do
      phoenix_links = Links.all(user, tags: ["phoenix"])
      assert length(phoenix_links) == 1

      elixir_links = Links.all(user, tags: ["elixir"])
      assert length(elixir_links) == 2
    end

    test "all/1 with date range filter returns matching links", %{user: user} do
      from = DateTime.add(DateTime.utc_now(), -1, :day)
      links = Links.all(user, from: from)
      assert length(links) == 1
    end
  end

  describe "recent/1 with account age filter" do
    setup do
      # Create users with different account ages
      # 60 days old (should be included)
      old_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(old_user.id, 60)
      # Exactly 30 days old (should be included)
      boundary_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(boundary_user.id, 30)
      # 10 days old (should be excluded)
      new_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(new_user.id, 10)

      # Create recent links for each user
      {:ok, old_user_link} =
        Links.create_link(old_user, %{
          url: "https://example.com/old",
          title: "Old User Link",
          tags: ["test"]
        })

      {:ok, boundary_user_link} =
        Links.create_link(boundary_user, %{
          url: "https://example.com/boundary",
          title: "Boundary User Link",
          tags: ["test"]
        })

      {:ok, new_user_link} =
        Links.create_link(new_user, %{
          url: "https://example.com/new",
          title: "New User Link",
          tags: ["test"]
        })

      assert %{failure: 0} = Oban.drain_queue(queue: :default)

      %{
        old_user_link: old_user_link,
        boundary_user_link: boundary_user_link,
        new_user_link: new_user_link
      }
    end

    test "excludes links from users created within 30 days", %{
      old_user_link: old,
      boundary_user_link: boundary,
      new_user_link: new
    } do
      recent_links = Links.recent([]) |> Linkhut.Repo.all()

      # Should only include links from users 30+ days old
      link_urls = Enum.map(recent_links, & &1.url)

      assert old.url in link_urls
      assert boundary.url in link_urls
      refute new.url in link_urls
    end
  end

  describe "recent/1 with configurable account_age_days" do
    setup do
      old_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(old_user.id, 60)

      new_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(new_user.id, 10)

      {:ok, old_link} =
        Links.create_link(old_user, %{
          url: "https://example.com/old-config",
          title: "Old Config Link",
          tags: ["test"]
        })

      {:ok, new_link} =
        Links.create_link(new_user, %{
          url: "https://example.com/new-config",
          title: "New Config Link",
          tags: ["test"]
        })

      assert %{failure: 0} = Oban.drain_queue(queue: :default)

      %{old_link: old_link, new_link: new_link}
    end

    test "respects overridden account_age_days", %{old_link: old, new_link: new} do
      # With default (30 days), new user's link should be excluded
      recent_urls =
        Links.recent([]) |> Linkhut.Repo.all() |> Enum.map(& &1.url)

      assert old.url in recent_urls
      refute new.url in recent_urls

      # Override to 5 days — now the 10-day-old account passes
      Linkhut.Config.put_override(Linkhut.Moderation, :account_age_days, 5)

      recent_urls =
        Links.recent([]) |> Linkhut.Repo.all() |> Enum.map(& &1.url)

      assert old.url in recent_urls
      assert new.url in recent_urls
    end

    test "account_age_days: 0 disables quarantine", %{old_link: old, new_link: new} do
      Linkhut.Config.put_override(Linkhut.Moderation, :account_age_days, 0)

      recent_urls =
        Links.recent([]) |> Linkhut.Repo.all() |> Enum.map(& &1.url)

      assert old.url in recent_urls
      assert new.url in recent_urls
    end
  end

  describe "popular/2 with account age filter" do
    setup do
      old_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(old_user.id, 60)

      new_user = AccountsFixtures.user_fixture()
      AccountsFixtures.override_user_inserted_at(new_user.id, 10)

      # Popular links need saves >= 3 from different users, plus rank == 1.0
      # in the public_links materialized view. This is hard to set up purely
      # via the Links context, so we verify the WHERE clause is present by
      # checking that the query includes the account-age filter.
      # We do a simpler smoke test: create links and verify new accounts are
      # excluded from the query result.
      {:ok, old_link} =
        Links.create_link(old_user, %{
          url: "https://example.com/old-pop",
          title: "Old Popular Link",
          tags: ["test"]
        })

      {:ok, new_link} =
        Links.create_link(new_user, %{
          url: "https://example.com/new-pop",
          title: "New Popular Link",
          tags: ["test"]
        })

      assert %{failure: 0} = Oban.drain_queue(queue: :default)

      %{old_link: old_link, new_link: new_link}
    end

    test "excludes links from new accounts", %{new_link: new} do
      popular_urls =
        Links.popular([]) |> Linkhut.Repo.all() |> Enum.map(& &1.url)

      refute new.url in popular_urls
    end
  end

  describe "link_stats/1" do
    setup do
      user = AccountsFixtures.user_fixture()
      %{user: user}
    end

    test "returns zeroes for user with no links", %{user: user} do
      stats = Links.link_stats(user)
      assert stats.total == 0
      assert stats.private == 0
      assert stats.unread == 0
    end

    test "counts total, private, and unread links", %{user: user} do
      Links.create_link(user, %{url: "https://a.com", title: "A", is_private: false})
      Links.create_link(user, %{url: "https://b.com", title: "B", is_private: true})

      Links.create_link(user, %{
        url: "https://c.com",
        title: "C",
        is_private: false,
        is_unread: true
      })

      stats = Links.link_stats(user)
      assert stats.total == 3
      assert stats.private == 1
      assert stats.unread == 1
    end

    test "does not count other users' links", %{user: user} do
      other = AccountsFixtures.user_fixture()
      Links.create_link(other, %{url: "https://other.com", title: "Other", is_private: true})
      Links.create_link(user, %{url: "https://mine.com", title: "Mine"})

      stats = Links.link_stats(user)
      assert stats.total == 1
      assert stats.private == 0
    end
  end

  describe "url_detail/2" do
    setup do
      alice = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      bob = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()

      url = "https://example.com/shared"
      alice_saved_at = DateTime.add(DateTime.utc_now(), -90, :day)
      bob_saved_at = DateTime.add(DateTime.utc_now(), -30, :day)

      {:ok, alice_link} =
        Links.create_link(alice, %{
          url: url,
          title: "Original Title",
          tags: ["elixir", "tutorial"],
          is_private: false,
          inserted_at: alice_saved_at
        })

      {:ok, bob_link} =
        Links.create_link(bob, %{
          url: url,
          title: "Updated Title",
          tags: ["elixir", "programming"],
          is_private: false,
          inserted_at: bob_saved_at
        })

      %{
        alice: alice,
        bob: bob,
        url: url,
        alice_link: alice_link,
        bob_link: bob_link,
        alice_saved_at: alice_saved_at,
        bob_saved_at: bob_saved_at
      }
    end

    test "returns a UrlDetail struct", %{url: url} do
      assert %UrlDetail{} = Links.url_detail(url)
    end

    test "returns nil for URL with no bookmarks" do
      assert Links.url_detail("https://nonexistent.example.com") == nil
    end

    test "returns nil when only private bookmarks exist" do
      user = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      url = "https://private-only.example.com"

      Links.create_link(user, %{
        url: url,
        title: "Private",
        is_private: true
      })

      assert Links.url_detail(url) == nil
    end

    test "returns correct total_saves count", %{url: url} do
      detail = Links.url_detail(url)
      assert detail.total_saves == 2
    end

    test "returns first_save with correct username and timestamp", %{
      url: url,
      alice: alice,
      alice_saved_at: alice_saved_at
    } do
      detail = Links.url_detail(url)
      assert detail.first_save.username == alice.username

      assert DateTime.truncate(detail.first_save.saved_at, :second) ==
               DateTime.truncate(alice_saved_at, :second)
    end

    test "returns latest_save with correct username and timestamp", %{
      url: url,
      bob: bob,
      bob_saved_at: bob_saved_at
    } do
      detail = Links.url_detail(url)
      assert detail.latest_save.username == bob.username

      assert DateTime.truncate(detail.latest_save.saved_at, :second) ==
               DateTime.truncate(bob_saved_at, :second)
    end

    test "returns title from most recent bookmark", %{url: url} do
      detail = Links.url_detail(url)
      assert detail.title == "Updated Title"
    end

    test "returns current_user_bookmark when option provided", %{url: url, alice: alice} do
      detail = Links.url_detail(url, current_user_id: alice.id)
      assert detail.current_user_bookmark != nil
      assert detail.current_user_bookmark.url == url
    end

    test "returns nil for current_user_bookmark when user hasn't saved", %{url: url} do
      other = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      detail = Links.url_detail(url, current_user_id: other.id)
      assert detail.current_user_bookmark == nil
    end

    test "includes current user's private bookmark in current_user_bookmark", %{alice: alice} do
      priv_url = "https://private-test.example.com"

      Links.create_link(alice, %{
        url: priv_url,
        title: "My Private",
        is_private: true
      })

      # Another user has a public bookmark so url_detail returns non-nil
      bob = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()

      Links.create_link(bob, %{
        url: priv_url,
        title: "Bob's Public",
        is_private: false
      })

      detail = Links.url_detail(priv_url, current_user_id: alice.id)
      assert detail.current_user_bookmark != nil
      assert detail.current_user_bookmark.is_private == true
    end

    test "returns only tags used by multiple users", %{url: url} do
      detail = Links.url_detail(url)
      tags = detail.common_tags

      # "elixir" appears in both bookmarks (count 2); "tutorial" and
      # "programming" appear once each and are excluded
      assert tags == [%{tag: "elixir", count: 2}]
    end

    test "excludes private and single-use tags from common_tags" do
      user = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      other = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      url = "https://tag-test.example.com"

      Links.create_link(user, %{
        url: url,
        title: "Private",
        tags: ["secret-tag", "shared-tag"],
        is_private: true
      })

      Links.create_link(other, %{
        url: url,
        title: "Public A",
        tags: ["public-tag", "shared-tag"],
        is_private: false
      })

      third = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()

      Links.create_link(third, %{
        url: url,
        title: "Public B",
        tags: ["shared-tag"],
        is_private: false
      })

      detail = Links.url_detail(url)
      tag_names = Enum.map(detail.common_tags, & &1.tag)
      # "shared-tag" appears in 2 public bookmarks (count > 1)
      assert "shared-tag" in tag_names
      # "public-tag" appears only once publicly
      refute "public-tag" in tag_names
      # "secret-tag" is private
      refute "secret-tag" in tag_names
    end

    test "returns domain_saves count", %{url: url, alice: alice} do
      # Add another link from same domain
      Links.create_link(alice, %{
        url: "https://example.com/other-page",
        title: "Other Page",
        is_private: false
      })

      detail = Links.url_detail(url)
      # 3 exactly: alice's shared, bob's shared, alice's other page
      assert detail.domain_saves == 3
    end

    test "returns weekly activity buckets with gap filling", %{url: url} do
      detail = Links.url_detail(url)
      assert %{granularity: :week, buckets: buckets} = detail.activity
      assert buckets != []

      for bucket <- buckets do
        assert %{period: %DateTime{}, count: count} = bucket
        assert count >= 0
      end

      # At least one bucket has saves
      assert Enum.any?(buckets, &(&1.count > 0))

      # Buckets extend to the current period
      last = List.last(buckets)
      assert DateTime.compare(last.period, DateTime.utc_now()) != :gt
    end

    test "returns monthly activity buckets for old URLs" do
      alice = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      bob = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      url = "https://old-url.example.com"

      Links.create_link(alice, %{
        url: url,
        title: "Old",
        is_private: false,
        inserted_at: DateTime.add(DateTime.utc_now(), -365, :day)
      })

      Links.create_link(bob, %{
        url: url,
        title: "Recent",
        is_private: false
      })

      detail = Links.url_detail(url)
      assert %{granularity: :month, buckets: buckets} = detail.activity
      assert buckets != []
      assert Enum.any?(buckets, &(&1.count > 0))
    end

    test "returns single save correctly" do
      user = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      url = "https://single-save.example.com"

      Links.create_link(user, %{
        url: url,
        title: "Solo",
        is_private: false
      })

      detail = Links.url_detail(url)
      assert detail.total_saves == 1
      assert detail.first_save.username == user.username
      assert detail.latest_save.username == user.username
    end

    test "includes bookmarks from unconfirmed users" do
      confirmed = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      unconfirmed = AccountsFixtures.user_fixture()
      url = "https://unconfirmed-test.example.com"

      Links.create_link(confirmed, %{
        url: url,
        title: "Confirmed User",
        is_private: false
      })

      Links.create_link(unconfirmed, %{
        url: url,
        title: "Unconfirmed User",
        is_private: false
      })

      detail = Links.url_detail(url)
      assert detail.total_saves == 2
    end

    test "excludes bookmarks from banned users" do
      active = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()
      banned = AccountsFixtures.user_fixture() |> AccountsFixtures.activate_user()

      Linkhut.Accounts.User.ban_user(banned)
      |> Linkhut.Repo.update!()

      url = "https://banned-test.example.com"

      Links.create_link(active, %{
        url: url,
        title: "Active User",
        is_private: false
      })

      Links.create_link(banned, %{
        url: url,
        title: "Banned User",
        is_private: false
      })

      detail = Links.url_detail(url)
      assert detail.total_saves == 1
      assert detail.first_save.username == active.username
    end
  end

  describe "maybe_clean_url/2" do
    test "strips tracking params with string keys when preference enabled" do
      attrs = %{"url" => "https://example.com?utm_source=twitter&ref=top", "title" => "Test"}
      prefs = %{strip_tracking_params: true}
      result = Links.maybe_clean_url(attrs, prefs)
      assert result["url"] == "https://example.com?ref=top"
      assert result["title"] == "Test"
    end

    test "strips tracking params with atom keys when preference enabled" do
      attrs = %{url: "https://example.com?fbclid=abc123&page=1", title: "Test"}
      prefs = %{strip_tracking_params: true}
      result = Links.maybe_clean_url(attrs, prefs)
      assert result.url == "https://example.com?page=1"
      assert result.title == "Test"
    end

    test "returns attrs unchanged when preference disabled" do
      attrs = %{"url" => "https://example.com?utm_source=twitter", "title" => "Test"}
      prefs = %{strip_tracking_params: false}
      assert Links.maybe_clean_url(attrs, prefs) == attrs
    end

    test "returns attrs unchanged when no URL key" do
      attrs = %{"title" => "Test"}
      prefs = %{strip_tracking_params: true}
      assert Links.maybe_clean_url(attrs, prefs) == attrs
    end
  end

  describe "delete_link/1" do
    setup do
      user = AccountsFixtures.user_fixture()

      {:ok, link} =
        Links.create_link(user, %{
          url: "https://example.com/delete-test",
          title: "Delete Test",
          tags: ["test"],
          is_private: true
        })

      %{user: user, link: link}
    end

    test "marks snapshots as pending_deletion and enqueues cleanup job", %{link: link} do
      snapshot = insert(:snapshot, link_id: link.id, state: :complete)

      assert {:ok, _} = Links.delete_link(link)

      updated = Repo.get(Linkhut.Archiving.Snapshot, snapshot.id)
      assert updated.state == :pending_deletion
      assert updated.link_id == nil

      assert_enqueued(worker: Linkhut.Archiving.Workers.StorageCleaner)
    end

    test "succeeds when link has no snapshots", %{link: link} do
      assert {:ok, _} = Links.delete_link(link)
    end
  end

end
