defmodule Linkhut.LinksTest do
  use Linkhut.DataCase
  alias Linkhut.Links
  alias Linkhut.Links.Link
  alias Linkhut.AccountsFixtures

  describe "create_link/2" do
    setup do
      user = AccountsFixtures.user_fixture()

      valid_attrs = %{
        url: "https://example.com/test",
        title: "Test Title",
        notes: "Some **markdown** content.",
        tags: ["elixir", "test"],
        is_private: true,
        is_unread: false
      }

      %{user: user, valid_attrs: valid_attrs}
    end

    test "successfully creates a link", %{user: user, valid_attrs: attrs} do
      assert {:ok, %Link{} = link} = Links.create_link(user, attrs)
      assert link.url == "https://example.com/test"
      assert link.title == "Test Title"
      assert link.notes == "Some **markdown** content."
    end

    test "requires url", %{user: user, valid_attrs: attrs} do
      required = [:url]

      for field <- required do
        invalid_attrs = Map.delete(attrs, field)
        {:error, changeset} = Links.create_link(user, invalid_attrs)
        refute changeset.valid?
        assert Access.get(errors_on(changeset), field) != []
      end
    end

    test "url must be valid with scheme and host", %{user: user} do
      for {invalid_url, error_msg} <- [
            {"example.com", "is missing a scheme"},
            {"https:", "is missing a host"},
            {"", "can't be blank"}
          ] do
        {:error, changeset} =
          Links.create_link(user, %{
            url: invalid_url,
            title: "Test",
            is_private: true
          })

        refute changeset.valid?
        assert %{url: [error]} = errors_on(changeset)
        assert error == error_msg
      end
    end

    test "notes generate notes_html", %{user: user, valid_attrs: attrs} do
      {:ok, link} = Links.create_link(user, attrs)

      assert link.notes_html =~ "<p>\nSome <strong>markdown</strong> content.</p>\n"
    end

    test "title is autogenerated from URL if not provided", %{user: user, valid_attrs: attrs} do
      for {html, idx} <-
            Enum.with_index([
              "<html><head><title>Fetched Title</title></head></html>",
              "<html><head><title>Not this title</title><meta property=\"og:title\" content=\"Fetched Title\" /></head></html>",
              "<html><body><h1>Fetched Title</h1><h1>Not the fetched title</h1></body></html>"
            ]) do
        Req.Test.stub(Linkhut.Links.Link, fn conn ->
          Req.Test.html(conn, html)
        end)

        attrs = Map.drop(attrs, [:title])
        attrs = Map.put(attrs, :url, "http://example.com/#{idx}")

        {:ok, link} = Links.create_link(user, attrs)
        assert link.url == "http://example.com/#{idx}"
        assert link.title == "Fetched Title"
      end
    end

    test "title fallback to path or host on failed fetch", %{user: user, valid_attrs: attrs} do
      for {url, title} <- [
            {"https://example.com/foo/bar.pdf", "bar.pdf"},
            {"https://example.com", "example.com"},
            {"https://foo.example.com", "foo.example.com"},
            {"http://localhost:8080", "localhost"},
            {"http://127.0.0.1:8080", "127.0.0.1"},
            {"http://10.0.0.1", "10.0.0.1"},
            {"http://192.168.0.1/", "192.168.0.1"},
            {"http://172.31.0.1/foo/", "foo"},
            {"http://[fc00::1]", "fc00::1"},
            {"http://[::1]:8080", "::1"}
          ] do
        Req.Test.stub(Linkhut.Links.Link, fn conn ->
          Req.Test.transport_error(conn, :closed)
        end)

        attrs = Map.drop(attrs, [:title])
        attrs = Map.put(attrs, :url, url)

        {:ok, link} = Links.create_link(user, attrs)
        assert link.title == title
      end
    end

    test "title is fallback to path or host on failed fetch", %{user: user, valid_attrs: attrs} do
      Req.Test.stub(Linkhut.Links.Link, fn conn ->
        Req.Test.transport_error(conn, :timeout)
      end)

      attrs = Map.drop(attrs, [:title])
      attrs = Map.put(attrs, :url, "https://example.com/foo/bar")

      {:ok, link} = Links.create_link(user, attrs)
      assert link.title == "bar"
    end

    test "deduplicates tags case-insensitively and preserves 'unread'", %{
      user: user,
      valid_attrs: attrs
    } do
      tags = ["Elixir", "elixir", "unread"]
      {:ok, link} = Links.create_link(user, Map.put(attrs, :tags, tags))
      assert link.tags == ["Elixir", "unread"]
    end

    test "adds 'unread' tag if is_unread is true", %{user: user, valid_attrs: attrs} do
      attrs = Map.put(attrs, :is_unread, true)
      {:ok, link} = Links.create_link(user, attrs)
      assert "unread" in link.tags
    end

    test "enforces max length on title and notes", %{user: user, valid_attrs: attrs} do
      {:error, changeset} =
        Links.create_link(user, %{
          attrs
          | title: String.duplicate("a", 300),
            notes: String.duplicate("b", 2000)
        })

      refute changeset.valid?
      assert "should be at most 255 character(s)" in errors_on(changeset).title
      assert "should be at most 1024 character(s)" in errors_on(changeset).notes
    end
  end

  describe "update_link/2" do
    setup context do
      user = AccountsFixtures.user_fixture()

      valid_attrs =
        %{
          url: "https://example.com/test",
          title: "Test Title",
          notes: "Some **markdown** content.",
          tags: ["elixir", "test"],
          is_private: true,
          is_unread: false
        }
        |> Map.merge(Map.get(context, :extra_attrs, %{}))

      {:ok, link} = Links.create_link(user, valid_attrs)

      %{user: user, link: link, valid_attrs: valid_attrs}
    end

    @tag extra_attrs: %{tags: ["unread"]}
    test "removes 'unread' tag if is_unread is false", %{link: link, valid_attrs: attrs} do
      attrs = Map.put(attrs, :is_unread, false)
      {:ok, link} = Links.update_link(link, attrs)
      refute "unread" in link.tags
      refute link.is_unread
    end

    test "is_unread is set if tags include 'unread'", %{link: link, valid_attrs: attrs} do
      attrs = Map.put(attrs, :tags, ["elixir", "unread"])
      {:ok, link} = Links.update_link(link, attrs)
      assert link.is_unread
    end
  end
end
