services:
  postgres:
    image: postgres:15-alpine
    hostname: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  linkhut:
    image: matiaslb/linkhut:edge
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - linkhut_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  linkhut_data:
